services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-modulo-8}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-modulo-8}
      POSTGRES_DB: ${POSTGRES_DB:-modulo-8}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://modulo-8:modulo-8@db:5432/modulo-8
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - db

volumes:
  db_data:
